#text summarization 
from transformers import pipeline

summarizer = pipeline("summarization", model = "google-t5/t5-base", tokenizer="google-t5/t5-base", framework="tf")
res = summarizer("""Spring Boot AI generator is a tool that helps developers create Spring Boot applications with AI capabilities. It provides a set of pre-built components that can be used to add AI features to applications, such as chatbots, recommendation engines, and sentiment analysis.The Spring Boot AI generator is based on the Spring AI framework, 
                 which is a Java library that provides a set of APIs for developing AI applications. The generator makes it easy to use these APIs by providing a graphical user interface (GUI) and a set of templates.To use the Spring Boot AI generator, developers first need to install the Spring AI framework. Once the framework is installed, developers can create a new Spring Boot project using the generator. The generator will then guide the developer through the process of adding AI features to the application.The Spring Boot AI generator is a powerful tool that can help developers create Spring Boot applications with AI capabilities. 
                 It provides a set of pre-built components that can be used to add AI features to applications, such as chatbots, recommendation engines, and sentiment analysis.If you are a developer who is interested in creating Spring Boot applications with AI capabilities, then the Spring Boot AI generator is a great tool to consider. 
                 It provides a set of pre-built components that can be used to add AI features to applications, such as chatbots, recommendation engines, and sentiment analysis.The holistic view of combining Generative AI in Spring Boot is essential for creating applications that are both functional and intelligent. 
                 Spring Boot’s flexibility and extensibility makes it a valuable choice for building the infrastructure and user interfaces of Generative AI applications, allowing developers to focus on the AI model’s core functionality rather than low-level application development concerns.Spring Boot aids Generative AI applications by simplifying web-based interfaces, facilitating integration, scalability, and security. Its rapid development capabilities and support for microservices architecture enhance the efficiency of building and deploying AI models.we were able to bring the full stack Spring Boot application that stores and handles data in Cloud Spanner, 
                 to generate poses using Google Cloud Vertex AI’s Imagen API in an interactive client application deployed in Cloud Run. By reusing the Cloud Spanner ORM and data from our previous application, we significantly accelerated the development process for this Generative AI image generation app. We began by establishing a robust data infrastructure using Google Cloud’s Spanner ORM, creating a strong foundation of data that is used to generate images using Vertex AI’s generative AI API.Spring Boot automatically configures your application based on the dependencies you have added to the project by using EnableAutoConfiguration annotation. For example, if MySQL database is on your classpath, but you have not configured any database connection, then Spring Boot auto-configures an in-memory database.
 """
, min_length=70, max_length= 100)
print("-------------------------------------------------------------")

print(res)
